"""added field provider_id in players table.

Revision ID: 06607b24bb63
Revises: c312ac3940b5
Create Date: 2026-06-13 03:21:50.084390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06607b24bb63'
down_revision: Union[str, Sequence[str], None] = 'c312ac3940b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('provider_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'provider_id')
    # ### end Alembic commands ###
