"""dropped team_wallets table and remove wallet column from team table

Revision ID: 09184b8af4c0
Revises: 44f5f95aa94f
Create Date: 2026-08-28 13:32:44.127404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09184b8af4c0'
down_revision: Union[str, Sequence[str], None] = '44f5f95aa94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
