"""added tournaments_id into tournament_roster table

Revision ID: 0b241de5d06b
Revises: 2877faa8b702
Create Date: 2026-08-28 13:47:38.617178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b241de5d06b'
down_revision: Union[str, Sequence[str], None] = '2877faa8b702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_roster', sa.Column('tournament_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tournament_roster', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_roster', type_='foreignkey')
    op.drop_column('tournament_roster', 'tournament_id')
    # ### end Alembic commands ###
