"""updated player model and added relationship for teammembers

Revision ID: 107d64fc283f
Revises: e57acb0c8698
Create Date: 2026-07-08 10:00:17.492962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107d64fc283f'
down_revision: Union[str, Sequence[str], None] = 'e57acb0c8698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
