"""update team model included region to be nullable

Revision ID: 109e9ed0f69f
Revises: 8c28ce665093
Create Date: 2026-07-08 11:28:20.791197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109e9ed0f69f'
down_revision: Union[str, Sequence[str], None] = '8c28ce665093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'region',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_teams_region'), table_name='teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_teams_region'), 'teams', ['region'], unique=False)
    op.alter_column('teams', 'region',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
