"""modified grace_period and check_in constraints from Integer to String

Revision ID: 175daaa0a961
Revises: 99a6aece1128
Create Date: 2026-08-12 23:40:20.515887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '175daaa0a961'
down_revision: Union[str, Sequence[str], None] = '99a6aece1128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'check_in',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tournaments', 'grace_period',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tournaments', 'entry_fee',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'entry_fee',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('tournaments', 'grace_period',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=True)
    op.alter_column('tournaments', 'check_in',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
