"""removed field player_code from table players

Revision ID: 18fa602c9135
Revises: 8376f6d8a693
Create Date: 2026-06-05 21:38:17.106742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18fa602c9135'
down_revision: Union[str, Sequence[str], None] = '8376f6d8a693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('players_player_code_key'), 'players', type_='unique')
    op.drop_column('players', 'player_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('player_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('players_player_code_key'), 'players', ['player_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
