"""update the players model added MLBB credentials column and profile column

Revision ID: 22cee2ad98a0
Revises: 44c00b1fb15c
Create Date: 2026-09-01 23:44:00.972608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "22cee2ad98a0"
down_revision: Union[str, Sequence[str], None] = "44c00b1fb15c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("username", sa.String(length=50), nullable=True))
    op.add_column("players", sa.Column("mlbb_id", sa.String(length=50), nullable=True))
    op.add_column(
        "players", sa.Column("mlbb_server", sa.String(length=20), nullable=True)
    )
    op.add_column("players", sa.Column("mlbb_level", sa.Integer(), nullable=True))
    op.add_column("players", sa.Column("profile_url", sa.String(), nullable=True))
    op.add_column("players", sa.Column("profile_public_id", sa.String(), nullable=True))
    op.add_column(
        "players", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,server_default=sa.text("CURRENT_TIMESTAMP"))
    )
    op.alter_column("players", "verified", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "players", "is_membership_active", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column("players", "is_banned", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("players", "role", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "players",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_unique_constraint(
        "uq_player_mlbb_id_server", "players", ["mlbb_id", "mlbb_server"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_player_mlbb_id_server", "players", type_="unique")
    op.alter_column(
        "players",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column("players", "role", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("players", "is_banned", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "players", "is_membership_active", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column("players", "verified", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("players", "updated_at")
    op.drop_column("players", "profile_public_id")
    op.drop_column("players", "profile_url")
    op.drop_column("players", "mlbb_level")
    op.drop_column("players", "mlbb_server")
    op.drop_column("players", "mlbb_id")
    op.drop_column("players", "username")
    # ### end Alembic commands ###
