"""add pending registration

Revision ID: 230dd3a3b521
Revises: 496fc70b2319
Create Date: 2026-06-06 23:06:38.863136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230dd3a3b521'
down_revision: Union[str, Sequence[str], None] = '496fc70b2319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('verification_token')
    )
    op.alter_column('players', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('pending_registration')
    # ### end Alembic commands ###
