"""added team_id into tournament roster table

Revision ID: 2877faa8b702
Revises: 09184b8af4c0
Create Date: 2026-08-28 13:43:10.325136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2877faa8b702'
down_revision: Union[str, Sequence[str], None] = '09184b8af4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_roster', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tournament_roster', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_roster', type_='foreignkey')
    op.drop_column('tournament_roster', 'team_id')
    # ### end Alembic commands ###
