"""updated team_contribution_table status from default to server_default.

Revision ID: 44c00b1fb15c
Revises: 94de17cc587b
Create Date: 2026-09-01 12:05:35.397168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c00b1fb15c'
down_revision: Union[str, Sequence[str], None] = '94de17cc587b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_tournament_contribution', sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='teamtournamentcontributionstatus'), server_default='PENDING', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_tournament_contribution', 'status')
    # ### end Alembic commands ###
