"""created tables

Revision ID: 44f5f95aa94f
Revises: 
Create Date: 2026-08-28 00:37:06.246894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f5f95aa94f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=False),
    sa.Column('token_expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent', sa.String(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_resent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resent_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('is_membership_active', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('player_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('refresh_jti', sa.String(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_sessions_refresh_jti'), 'player_sessions', ['refresh_jti'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('tag', sa.String(length=10), nullable=False),
    sa.Column('logo_public_id', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('banner_public_id', sa.String(length=255), nullable=True),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', 'INVITE_ONLY', name='teamvisibility'), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'BANNED', 'DISBANDED', 'ARCHIVED', name='teamstatus'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('banned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['banned_by'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['captain_id'], ['players.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['players.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_region_status', 'teams', ['country', 'region', 'status'], unique=False)
    op.create_index('idx_team_status_visibility', 'teams', ['status', 'visibility'], unique=False)
    op.create_index(op.f('ix_teams_captain_id'), 'teams', ['captain_id'], unique=False)
    op.create_index(op.f('ix_teams_country'), 'teams', ['country'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_index(op.f('ix_teams_status'), 'teams', ['status'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(length=150), nullable=False),
    sa.Column('game_name', sa.String(length=100), nullable=False),
    sa.Column('tournament_type', sa.String(length=50), nullable=False),
    sa.Column('team_format', sa.String(length=50), nullable=False),
    sa.Column('min_teams', sa.Integer(), nullable=False),
    sa.Column('max_teams', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform_fee', sa.String(length=50), nullable=True),
    sa.Column('winner_share', sa.String(length=50), nullable=True),
    sa.Column('runner_up_share', sa.String(length=50), nullable=True),
    sa.Column('reg_open_date', sa.Date(), nullable=False),
    sa.Column('reg_open_time', sa.Time(), nullable=False),
    sa.Column('reg_close_date', sa.Date(), nullable=False),
    sa.Column('reg_close_time', sa.Time(), nullable=False),
    sa.Column('tournament_start_date', sa.Date(), nullable=False),
    sa.Column('tournament_start_time', sa.Time(), nullable=False),
    sa.Column('tournament_end_date', sa.Date(), nullable=False),
    sa.Column('tournament_end_time', sa.Time(), nullable=False),
    sa.Column('check_in', sa.String(), nullable=True),
    sa.Column('grace_period', sa.String(), nullable=True),
    sa.Column('bracket_format', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('competition_type', sa.String(length=50), nullable=True),
    sa.Column('seeding_method', sa.String(length=50), nullable=True),
    sa.Column('entry_fee', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('prize_pool', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('minimum_account_level', sa.Integer(), nullable=True),
    sa.Column('minimum_rank', sa.String(length=50), nullable=True),
    sa.Column('registration_access', sa.String(length=50), nullable=True),
    sa.Column('registration_approval', sa.String(length=50), nullable=True),
    sa.Column('server', sa.String(length=50), nullable=False),
    sa.Column('background_image_url', sa.Text(), nullable=True),
    sa.Column('background_image_public_id', sa.String(length=255), nullable=True),
    sa.Column('banner_image_url', sa.Text(), nullable=True),
    sa.Column('banner_image_public_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('registration_status', sa.String(length=30), nullable=True),
    sa.Column('visibility_status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_name')
    )
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_table('join_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'EXPIRED', name='teamjoinrequeststatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'player_id', name='uq_team_player_request')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('CAPTAIN', 'CO_LEADER', 'PLAYER', 'SUBSTITUTE', name='teamrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LEFT', 'REMOVED', 'BANNED', name='teammemberstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_player', 'team_members', ['team_id', 'player_id'], unique=False)
    op.create_index('idx_team_role', 'team_members', ['team_id', 'role'], unique=False)
    op.create_index(op.f('ix_team_members_player_id'), 'team_members', ['player_id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_table('team_tournament_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'PAYMENT_PENDING', 'APPROVED', 'FAILED', 'CANCELLED', 'DISQUALIFIED', name='tournamentregistrationstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['captain_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deposit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_withdraw', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FROZEN', 'CLOSED', name='walletstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('tournament_roster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SELECTING', 'CONFIRMED', 'LOCKED', name='tournamentrosterstatus'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['locked_by'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['team_tournament_registration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id')
    )
    op.create_table('tournament_roster_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SELECTED', 'REMOVED', name='tournamentrosterplayerstatus'), nullable=False),
    sa.Column('tournament_readiness', sa.Enum('NOT_READY', 'READY', name='tournamentreadiness'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roster_id'], ['tournament_roster.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roster_id', 'player_id', name='uq_roster_player')
    )
    op.create_index(op.f('ix_tournament_roster_player_player_id'), 'tournament_roster_player', ['player_id'], unique=False)
    op.create_index(op.f('ix_tournament_roster_player_roster_id'), 'tournament_roster_player', ['roster_id'], unique=False)
    op.create_table('team_tournament_contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_player_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='teamtournamentcontributionstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roster_player_id'], ['tournament_roster_player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_tournament_contribution_roster_player_id'), 'team_tournament_contribution', ['roster_player_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=False),
    sa.Column('payment_type', sa.Enum('TOURNAMENT_CONTRIBUTION', name='paymenttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('contribution_id', sa.Integer(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['team_tournament_contribution.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['team_tournament_registration.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_payment_reference'), 'payments', ['payment_reference'], unique=True)
    op.create_table('payment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PROCESSING', 'SUCCESS', 'FAILED', name='paymentattemptstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('gateway_order_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_payments_payment_reference'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_team_tournament_contribution_roster_player_id'), table_name='team_tournament_contribution')
    op.drop_table('team_tournament_contribution')
    op.drop_index(op.f('ix_tournament_roster_player_roster_id'), table_name='tournament_roster_player')
    op.drop_index(op.f('ix_tournament_roster_player_player_id'), table_name='tournament_roster_player')
    op.drop_table('tournament_roster_player')
    op.drop_table('tournament_roster')
    op.drop_table('team_wallets')
    op.drop_table('team_tournament_registration')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_player_id'), table_name='team_members')
    op.drop_index('idx_team_role', table_name='team_members')
    op.drop_index('idx_team_player', table_name='team_members')
    op.drop_table('team_members')
    op.drop_table('join_request')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_teams_status'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_country'), table_name='teams')
    op.drop_index(op.f('ix_teams_captain_id'), table_name='teams')
    op.drop_index('idx_team_status_visibility', table_name='teams')
    op.drop_index('idx_team_region_status', table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_player_sessions_refresh_jti'), table_name='player_sessions')
    op.drop_table('player_sessions')
    op.drop_table('players')
    op.drop_table('pending_registration')
    # ### end Alembic commands ###
