"""added relation in tournament 'rounds'

Revision ID: 74f1d2d4a7b6
Revises: 8e1e974f65e3
Create Date: 2026-09-23 18:47:55.959994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f1d2d4a7b6'
down_revision: Union[str, Sequence[str], None] = '8e1e974f65e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
