"""added relationship between tournament and team registered tournament models

Revision ID: 7b053d285f05
Revises: bf94b1f6159e
Create Date: 2026-08-26 12:06:39.427068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b053d285f05'
down_revision: Union[str, Sequence[str], None] = 'bf94b1f6159e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
