"""modified pending registration table

Revision ID: 83df41abed7a
Revises: 230dd3a3b521
Create Date: 2026-06-07 00:06:41.668984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83df41abed7a'
down_revision: Union[str, Sequence[str], None] = '230dd3a3b521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_registration', sa.Column('token_expire_at', sa.DateTime(), nullable=False))
    op.add_column('pending_registration', sa.Column('email_sent', sa.Boolean(), nullable=True))
    op.add_column('pending_registration', sa.Column('email_sent_at', sa.DateTime(), nullable=True))
    op.drop_column('pending_registration', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_registration', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('pending_registration', 'email_sent_at')
    op.drop_column('pending_registration', 'email_sent')
    op.drop_column('pending_registration', 'token_expire_at')
    # ### end Alembic commands ###
