"""create team table

Revision ID: 8c28ce665093
Revises: 9dd7fd0935b3
Create Date: 2026-07-08 11:06:08.592012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c28ce665093'
down_revision: Union[str, Sequence[str], None] = '9dd7fd0935b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('tag', sa.String(length=10), nullable=False),
    sa.Column('logo_public_id', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('banner_public_id', sa.String(length=255), nullable=True),
    sa.Column('banner_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', 'INVITE_ONLY', name='teamvisibility'), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'BANNED', 'DISBANDED', 'ARCHIVED', name='teamstatus'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('banned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['banned_by'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['captain_id'], ['players.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['players.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_region_status', 'teams', ['country', 'region', 'status'], unique=False)
    op.create_index('idx_team_status_visibility', 'teams', ['status', 'visibility'], unique=False)
    op.create_index(op.f('ix_teams_captain_id'), 'teams', ['captain_id'], unique=False)
    op.create_index(op.f('ix_teams_country'), 'teams', ['country'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_index(op.f('ix_teams_region'), 'teams', ['region'], unique=False)
    op.create_index(op.f('ix_teams_status'), 'teams', ['status'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('CAPTAIN', 'CO_LEADER', 'PLAYER', 'SUBSTITUTE', name='teamrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LEFT', 'REMOVED', 'BANNED', name='teammemberstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_player', 'team_members', ['team_id', 'player_id'], unique=False)
    op.create_index('idx_team_role', 'team_members', ['team_id', 'role'], unique=False)
    op.create_index(op.f('ix_team_members_player_id'), 'team_members', ['player_id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_table('team_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deposit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_withdraw', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FROZEN', 'CLOSED', name='walletstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_wallets')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_player_id'), table_name='team_members')
    op.drop_index('idx_team_role', table_name='team_members')
    op.drop_index('idx_team_player', table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_teams_status'), table_name='teams')
    op.drop_index(op.f('ix_teams_region'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_country'), table_name='teams')
    op.drop_index(op.f('ix_teams_captain_id'), table_name='teams')
    op.drop_index('idx_team_status_visibility', table_name='teams')
    op.drop_index('idx_team_region_status', table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
