"""created tables for bracket and tournament round, match, evidence and results

Revision ID: 8e1e974f65e3
Revises: b2c3d51a883d
Create Date: 2026-09-23 18:24:27.711051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1e974f65e3'
down_revision: Union[str, Sequence[str], None] = 'b2c3d51a883d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'round_number', name='uq_tournament_round_number')
    )
    op.create_index(op.f('ix_tournament_round_tournament_id'), 'tournament_round', ['tournament_id'], unique=False)
    op.create_index('ix_tournament_round_tournament_status', 'tournament_round', ['tournament_id', 'status'], unique=False)
    op.create_table('tournament_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=True),
    sa.Column('team_b_id', sa.Integer(), nullable=True),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('team_a_readiness', sa.String(length=30), nullable=False),
    sa.Column('team_b_readiness', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['tournament_round.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'match_number', name='uq_round_match_number')
    )
    op.create_index(op.f('ix_tournament_match_round_id'), 'tournament_match', ['round_id'], unique=False)
    op.create_index('ix_tournament_match_round_status', 'tournament_match', ['round_id', 'status'], unique=False)
    op.create_index('ix_tournament_match_team_a', 'tournament_match', ['team_a_id'], unique=False)
    op.create_index('ix_tournament_match_team_b', 'tournament_match', ['team_b_id'], unique=False)
    op.create_table('tournament_match_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['tournament_match.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'game_number', name='uq_match_game_number')
    )
    op.create_index(op.f('ix_tournament_match_game_match_id'), 'tournament_match_game', ['match_id'], unique=False)
    op.create_table('tournament_match_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['tournament_match.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('tournament_game_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_game_id', sa.Integer(), nullable=False),
    sa.Column('screenshot_url', sa.Text(), nullable=False),
    sa.Column('screenshot_public_id', sa.String(length=255), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_game_id'], ['tournament_match_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['players.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tournament_game_evidence_game_status', 'tournament_game_evidence', ['match_game_id', 'status'], unique=False)
    op.create_index(op.f('ix_tournament_game_evidence_match_game_id'), 'tournament_game_evidence', ['match_game_id'], unique=False)
    op.create_table('tournament_game_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_game_id', sa.Integer(), nullable=False),
    sa.Column('winner_team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_game_id'], ['tournament_match_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_game_results')
    op.drop_index(op.f('ix_tournament_game_evidence_match_game_id'), table_name='tournament_game_evidence')
    op.drop_index('ix_tournament_game_evidence_game_status', table_name='tournament_game_evidence')
    op.drop_table('tournament_game_evidence')
    op.drop_table('tournament_match_result')
    op.drop_index(op.f('ix_tournament_match_game_match_id'), table_name='tournament_match_game')
    op.drop_table('tournament_match_game')
    op.drop_index('ix_tournament_match_team_b', table_name='tournament_match')
    op.drop_index('ix_tournament_match_team_a', table_name='tournament_match')
    op.drop_index('ix_tournament_match_round_status', table_name='tournament_match')
    op.drop_index(op.f('ix_tournament_match_round_id'), table_name='tournament_match')
    op.drop_table('tournament_match')
    op.drop_index('ix_tournament_round_tournament_status', table_name='tournament_round')
    op.drop_index(op.f('ix_tournament_round_tournament_id'), table_name='tournament_round')
    op.drop_table('tournament_round')
    # ### end Alembic commands ###
