"""create tournament table

Revision ID: 99a6aece1128
Revises: 54abcd5a9546
Create Date: 2026-08-12 22:22:40.709081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99a6aece1128'
down_revision: Union[str, Sequence[str], None] = '54abcd5a9546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(length=150), nullable=False),
    sa.Column('game_name', sa.String(length=100), nullable=False),
    sa.Column('tournament_type', sa.String(length=50), nullable=False),
    sa.Column('team_format', sa.String(length=50), nullable=False),
    sa.Column('min_teams', sa.Integer(), nullable=False),
    sa.Column('max_teams', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform_fee', sa.String(length=50), nullable=True),
    sa.Column('winner_share', sa.String(length=50), nullable=True),
    sa.Column('runner_up_share', sa.String(length=50), nullable=True),
    sa.Column('reg_open_date', sa.Date(), nullable=False),
    sa.Column('reg_open_time', sa.Time(), nullable=False),
    sa.Column('reg_close_date', sa.Date(), nullable=False),
    sa.Column('reg_close_time', sa.Time(), nullable=False),
    sa.Column('tournament_start_date', sa.Date(), nullable=False),
    sa.Column('tournament_start_time', sa.Time(), nullable=False),
    sa.Column('tournament_end_date', sa.Date(), nullable=False),
    sa.Column('tournament_end_time', sa.Time(), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('grace_period', sa.Time(), nullable=True),
    sa.Column('bracket_format', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('competition_type', sa.String(length=50), nullable=True),
    sa.Column('seeding_method', sa.String(length=50), nullable=True),
    sa.Column('entry_fee', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('minimum_account_level', sa.Integer(), nullable=True),
    sa.Column('minimum_rank', sa.String(length=50), nullable=True),
    sa.Column('registration_access', sa.String(length=50), nullable=True),
    sa.Column('registration_approval', sa.String(length=50), nullable=True),
    sa.Column('server', sa.String(length=50), nullable=False),
    sa.Column('background_image_url', sa.Text(), nullable=True),
    sa.Column('background_image_public_id', sa.String(length=255), nullable=True),
    sa.Column('banner_image_url', sa.Text(), nullable=True),
    sa.Column('banner_image_public_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
