"""created payment security model to lock user from making further payment until lock reset

Revision ID: 9de63df455e6
Revises: 22cee2ad98a0
Create Date: 2026-09-05 16:41:34.353494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de63df455e6'
down_revision: Union[str, Sequence[str], None] = '22cee2ad98a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_payment_security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('lock_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_payment_security_player_id'), 'player_payment_security', ['player_id'], unique=True)
    op.add_column('payments', sa.Column('idempotency_key', sa.String(length=100), nullable=False))
    op.alter_column('payments', 'payment_reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.alter_column('payments', 'payment_reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('payments', 'idempotency_key')
    op.drop_index(op.f('ix_player_payment_security_player_id'), table_name='player_payment_security')
    op.drop_table('player_payment_security')
    # ### end Alembic commands ###
