"""updates the team model and created fields for storing cloudinary public id and secure url

Revision ID: a43a9ba2cd20
Revises: b3be67e784dc
Create Date: 2026-07-07 18:23:02.689332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43a9ba2cd20'
down_revision: Union[str, Sequence[str], None] = 'b3be67e784dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
