"""create models

Revision ID: add15e5fab34
Revises: 
Create Date: 2026-09-09 01:13:40.610514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add15e5fab34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_attempts', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('payment_attempts', sa.Column('payment_method', sa.String(length=30), nullable=True))
    op.add_column('payment_attempts', sa.Column('gateway', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_payment_attempts_status'), 'payment_attempts', ['status'], unique=False)
    op.add_column('payments', sa.Column('payment_type', sa.String(length=50), nullable=False))
    op.add_column('payments', sa.Column('status', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_payments_payment_type'), 'payments', ['payment_type'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_type'), table_name='payments')
    op.drop_column('payments', 'status')
    op.drop_column('payments', 'payment_type')
    op.drop_index(op.f('ix_payment_attempts_status'), table_name='payment_attempts')
    op.drop_column('payment_attempts', 'gateway')
    op.drop_column('payment_attempts', 'payment_method')
    op.drop_column('payment_attempts', 'status')
    # ### end Alembic commands ###
