"""added relation between tournament registration model and team model

Revision ID: b00304c42482
Revises: 802aa9a1d83d
Create Date: 2026-09-07 01:39:51.620535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b00304c42482'
down_revision: Union[str, Sequence[str], None] = '802aa9a1d83d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'entry_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('tournaments', 'entry_fee',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('tournaments', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('tournaments', 'registration_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('tournaments', 'visibility_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=False)
    op.alter_column('tournaments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('tournaments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_tournaments_created_by'), 'tournaments', ['created_by'], unique=False)
    op.create_index('ix_tournaments_game_status', 'tournaments', ['game_name', 'status'], unique=False)
    op.create_index('ix_tournaments_registration_status', 'tournaments', ['registration_status'], unique=False)
    op.create_index('ix_tournaments_registration_window', 'tournaments', ['registration_opens_at', 'registration_closes_at'], unique=False)
    op.create_index('ix_tournaments_starts_at', 'tournaments', ['starts_at'], unique=False)
    op.create_index('ix_tournaments_status', 'tournaments', ['status'], unique=False)
    op.create_index('ix_tournaments_visibility_status', 'tournaments', ['visibility_status'], unique=False)
    op.drop_constraint(op.f('tournaments_created_by_fkey'), 'tournaments', type_='foreignkey')
    op.create_foreign_key(None, 'tournaments', 'players', ['created_by'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='foreignkey')
    op.create_foreign_key(op.f('tournaments_created_by_fkey'), 'tournaments', 'players', ['created_by'], ['id'])
    op.drop_index('ix_tournaments_visibility_status', table_name='tournaments')
    op.drop_index('ix_tournaments_status', table_name='tournaments')
    op.drop_index('ix_tournaments_starts_at', table_name='tournaments')
    op.drop_index('ix_tournaments_registration_window', table_name='tournaments')
    op.drop_index('ix_tournaments_registration_status', table_name='tournaments')
    op.drop_index('ix_tournaments_game_status', table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_created_by'), table_name='tournaments')
    op.alter_column('tournaments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tournaments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tournaments', 'visibility_status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tournaments', 'registration_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tournaments', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tournaments', 'entry_fee',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('tournaments', 'entry_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
