"""added more column for postpone , registration extended and bracket generation status in tournament table

Revision ID: b2c3d51a883d
Revises: d0989dfcc978
Create Date: 2026-09-18 23:40:26.389032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c3d51a883d'
down_revision: Union[str, Sequence[str], None] = 'd0989dfcc978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('bracket_status', sa.String(length=30), nullable=True))
    op.add_column('tournaments', sa.Column('registration_extended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tournaments', sa.Column('registration_extension_reason', sa.Text(), nullable=True))
    op.add_column('tournaments', sa.Column('postponed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tournaments', sa.Column('postponement_reason', sa.Text(), nullable=True))
    op.add_column('tournaments', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tournaments', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'cancellation_reason')
    op.drop_column('tournaments', 'cancelled_at')
    op.drop_column('tournaments', 'postponement_reason')
    op.drop_column('tournaments', 'postponed_at')
    op.drop_column('tournaments', 'registration_extension_reason')
    op.drop_column('tournaments', 'registration_extended_at')
    op.drop_column('tournaments', 'bracket_status')
    # ### end Alembic commands ###
