"""added is_active field into Players model

Revision ID: bf94b1f6159e
Revises: e8299971cf75
Create Date: 2026-08-25 18:30:20.501783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf94b1f6159e'
down_revision: Union[str, Sequence[str], None] = 'e8299971cf75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_active')
    # ### end Alembic commands ###
