"""track verification email status and resend attempts

Revision ID: cb4e7d3f39dc
Revises: 96bf09867032
Create Date: 2026-06-09 13:25:22.576095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4e7d3f39dc'
down_revision: Union[str, Sequence[str], None] = '96bf09867032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_registration', sa.Column('last_resent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pending_registration', sa.Column('resent_count', sa.Integer(), nullable=True))
    op.add_column('pending_registration', sa.Column('last_error', sa.String(), nullable=True))
    op.alter_column('pending_registration', 'email_sent',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_registration', 'email_sent',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_column('pending_registration', 'last_error')
    op.drop_column('pending_registration', 'resent_count')
    op.drop_column('pending_registration', 'last_resent_at')
    # ### end Alembic commands ###
