"""fix payment models

Revision ID: d0989dfcc978
Revises: add15e5fab34
Create Date: 2026-09-13 15:02:51.528462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0989dfcc978'
down_revision: Union[str, Sequence[str], None] = 'add15e5fab34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_payment_attempt_payment_idempotency'), 'payment_attempts', type_='unique')
    op.drop_index(op.f('ix_payment_attempts_idempotency_key'), table_name='payment_attempts')
    op.create_index(op.f('ix_payment_attempts_idempotency_key'), 'payment_attempts', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_attempts_idempotency_key'), table_name='payment_attempts')
    op.create_index(op.f('ix_payment_attempts_idempotency_key'), 'payment_attempts', ['idempotency_key'], unique=False)
    op.create_unique_constraint(op.f('uq_payment_attempt_payment_idempotency'), 'payment_attempts', ['payment_id', 'idempotency_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
