"""fixed a typo in player model where teams was written as team

Revision ID: db424ee24e6c
Revises: 107d64fc283f
Create Date: 2026-07-08 10:01:51.015885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db424ee24e6c'
down_revision: Union[str, Sequence[str], None] = '107d64fc283f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
