"""fixed a typo in back populate value for tournament relationship in TeamTournamentRegistration Model

Revision ID: e31cec598ebe
Revises: 7b053d285f05
Create Date: 2026-08-26 12:11:39.776069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31cec598ebe'
down_revision: Union[str, Sequence[str], None] = '7b053d285f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
