"""add tournament status fields

Revision ID: e37b3beeca47
Revises: 175daaa0a961
Create Date: 2026-08-15 23:24:30.441554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37b3beeca47'
down_revision: Union[str, Sequence[str], None] = '175daaa0a961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('tournaments', sa.Column('registration_status', sa.String(length=30), nullable=False))
    op.add_column('tournaments', sa.Column('visibility_status', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'tournaments', ['tournament_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournaments', type_='unique')
    op.drop_column('tournaments', 'visibility_status')
    op.drop_column('tournaments', 'registration_status')
    op.drop_column('tournaments', 'status')
    # ### end Alembic commands ###
