"""updated team model removed tournamnet relation for now as no models is created for tournamnet specific module

Revision ID: e57acb0c8698
Revises: a43a9ba2cd20
Create Date: 2026-07-08 09:57:08.293565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57acb0c8698'
down_revision: Union[str, Sequence[str], None] = 'a43a9ba2cd20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
