"""added confirmed locked and substitute status values in enum type of tournament roster player table.

Revision ID: e60b22479a21
Revises: 0b241de5d06b
Create Date: 2026-08-31 22:30:37.242512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e60b22479a21'
down_revision: Union[str, Sequence[str], None] = '0b241de5d06b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
