"""created team tournament registration model

Revision ID: e8299971cf75
Revises: e37b3beeca47
Create Date: 2026-08-25 17:53:11.562746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8299971cf75'
down_revision: Union[str, Sequence[str], None] = 'e37b3beeca47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_tournament_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'PAYMENT_PENDING', 'APPROVED', 'FAILED', 'CANCELLED', 'DISQUALIFIED', name='tournamentregistrationstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['captain_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('tournaments', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tournaments', 'registration_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('tournaments', 'visibility_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'visibility_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tournaments', 'registration_status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('tournaments', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_table('team_tournament_registration')
    # ### end Alembic commands ###
