"""removed previously added enum values for tournament roster player removed confirmed,locked values 

Revision ID: ed95ecf7c889
Revises: e60b22479a21
Create Date: 2026-08-31 22:43:42.798935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed95ecf7c889'
down_revision: Union[str, Sequence[str], None] = 'e60b22479a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
